#!/bin/bash

#SBATCH --job-name=DL-EXAM1
#SBATCH -p GPU
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#   #SBATCH --exclusive
#SBATCH --cpus-per-task=12
#SBATCH --time=0-02:00:00
#SBATCH -A dssc
#	#SBATCH --mem-per-cpu=1500MB
#SBATCH --output=output1.out 
#SBATCH --error=error1.err

# Original 

# # Activate conda (change with your username and path)
# eval "$(/u/dssc/mtallone/scratch/miniconda/bin/conda shell.bash hook)"

# # Activate the pytorch environment
# conda activate pytorch

# # Run the python script
# cd python
# python brats1.py

# echo "🏁 Job completed!"


# Timed

echo "Job started at $(date)"

# Activate conda (change with your username and path)
start_time=$(date +%s)
eval "$(/u/dssc/mtallone/scratch/miniconda/bin/conda shell.bash hook)" &>> error1.err
conda activate pytorch &>> error1.err
end_time=$(date +%s)
echo "Conda environment activated in $(($end_time - $start_time)) seconds"

# Run the python script
cd python
python brats1.py

echo "🏁 Job completed at $(date)!"