#!/bin/bash

#SBATCH --job-name=dl-exam-train
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=0-01:00:00
#SBATCH -A dssc
#SBATCH -p GPU
#SBATCH --gres=gpu:1
#	#SBATCH --mem-per-cpu=1500MB
#SBATCH --output=output.out 
#SBATCH --error=error.err

# Activate conda (change with your username and path)
eval "$(/u/dssc/mtallone/scratch/miniconda/bin/conda shell.bash hook)"

# Activate the pytorch environment
conda activate pytorch

# Run the python script
python test.py

echo "🏁 | Job completed!"